#158423678  Add passenger's profile page
artorious/Ride-My-Way pull request #11
Opened 2018-06-20 21:59 UTC by artorious

#### What does this PR do?

Adds passengers' profile page which holds;
 
* All registration details about the passenger. 
* Active/open rides that passenger has requested
* Contact numbers for active drivers
* A past rides log (history)

#### Description of Task to be completed?

* Building (without functionality), the UI elements with HTML&CSS. 

#### How the app should be tested
On a webbrowser:

* [Download](https://github.com/artorious/Ride-My-Way/archive/ft-passenger-profile-158423678.zip) the repo
* Extract and navigate into the `Ride-My-Way` folder
* in the `UI` folder, open `passenger_profile.html` on a browser

On a  terminal (Linux):

* Install and set up git `sudo apt install git` 

* Clone the repository `git clone https://github.com/artorious/Ride-My-Way.git`

* Run `git checkout ft-passenger-profile-158423678`

* Run `cd Ride-My-Way/UI/`

* Open `passenger_profile.html` on a browser

#### Any background context you want to provide?
The UI has no functionality. 
Developed using HTML and CSS

#### What are the relevant pivotal tracker stories?
[#158423678](https://www.pivotaltracker.com/story/show/158423678)

#### Screenshots 

![1](https://user-images.githubusercontent.com/15730750/41686849-4ca37ed0-74ee-11e8-851b-9e978c5cde9b.png)

#### Questions:

2018-06-20 23:36 UTC, rethes commented
code looks good

2018-06-21 04:34 UTC, Ogollah commented
I feel like the profile page looks congested.

2018-06-21 16:47 UTC, LWanjiru requested changes
@artorious I am curious regarding the `active Rides` section, can a passenger have rides running concurrently? Also, as indicated in the previous PR reviews, please consider refactoring how the page looks and feels. I agree with Ogollah, there seems to be a lot going on on this page. Remember everything doesn't have to fit into one page, it can be done in different pages which would then be linked.

2018-06-21 16:47 UTC, LWanjiru commented on UI/passenger_profile.html
> +</html>
add new line here

2018-06-21 22:23 UTC, artorious commented
@rethes @Ogollah @LWanjiru Your input is much appreciated. I've made changes to improve readability and reduce congestion

![passprof](https://user-images.githubusercontent.com/15730750/41748513-e452d8f8-75ba-11e8-800d-0791c8b3159e.png)

2018-06-21 22:25 UTC, merged